### PR TITLE
scala 2.13 build

### PR DESCRIPTION
**Pull request by pjfanning**

### CODE REVIEW

**Review by yanns — APPROVED** [review]
💯

**Comment by pjfanning** [comment]
I don't know what is causing the travis build problem - it appears to be using an out of date copy of the .travis.yml file

**Comment by yanns** [comment]
I deleted the travis cache. Let's try again.

**Comment by yanns** [comment]
it still does not work 😭 
I don't understand.

**Comment by yanns** [comment]
Travis is looking at the `master` branch. strange.

Screenshot 2019-10-28 at 15 39 04

**Comment by yanns** [comment]
I decided to merge. I'm fed up losing my time with that.

**Pull request merged**
